import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Feed from "../components/Feed";
import Modal from "../components/Modal";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className=' bg-gray-50 h-screen overflow-auto'>
			<Head>
				<title>Instagram Clone</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div>
				<Header />
				<Feed />
				<Modal />
			</div>
		</div>
	);
}
